In [5]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator 
import os
import matplotlib.pyplot as plt
import cv2
from tensorflow.keras import layers
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten
%matplotlib inline

In [45]:
train_dir = r"D:\Dataset\S_B_R_images\train"
test_dir = r"D:\Dataset\S_B_R_images\test"
train_dir,test_dir

('D:\\Dataset\\S_B_R_images\\train', 'D:\\Dataset\\S_B_R_images\\test')

In [46]:
os.listdir(test_dir)

['bg', 'rt', 'sm']

In [47]:
train_datagen = ImageDataGenerator(
    rescale=1.0/255.0,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)
test_datagen = ImageDataGenerator(
    rescale=1.0/255.0
)

In [48]:
train_ge = train_datagen.flow_from_directory(train_dir,target_size = (150,150),batch_size=4)
test_ge = test_datagen.flow_from_directory(test_dir,target_size = (150,150),batch_size=4)

Found 30 images belonging to 3 classes.
Found 9 images belonging to 3 classes.


In [49]:
train_ge.class_indices

{'bg': 0, 'rt': 1, 'sm': 2}

In [50]:
train_ge.classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [51]:
test_ge.classes

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [52]:
model = Sequential()
model.add(layers.Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=(150,150,3)))
model.add(layers.MaxPool2D(2,2))

model.add(layers.Conv2D(64,kernel_size=(3,3),activation='relu'))
model.add(layers.MaxPool2D(2,2))


model.add(layers.Conv2D(64,kernel_size=(3,3),activation='relu'))
model.add(layers.MaxPool2D(2,2))

model.add(Flatten())

model.add(layers.Dense(128,activation='relu'))
model.add(layers.Dropout(0.5))

model.add(layers.Dense(3,activation='softmax'))

In [53]:
'''
    class_mode: One of "categorical",
    "binary", "sparse", "input", or None. Default: 
    "categorical". Determines the type of label arrays that are returned: - 
    "categorical" will be 2D one-hot encoded labels, - 
    "binary" will be 1D binary labels, 
    "sparse" will be 1D integer labels, - "
    input" will be images identical to input images 
    (mainly used to work with autoencoders). - 
    If None, no labels are returned 
    (the generator will only yield batches of image data, 
    which is useful to use with model.predict_generator()). 
    Please note that in case of class_mode None, 
    the data still needs to reside in a subdirectory of directory for it to work correctly.
'''
'''
    So you should use categorical_crossentropy as loss function 
    if you choose categorical for class_mode, 
    and sparse_categorical_crossentropy if you choose sparse
'''
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [54]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 148, 148, 32)      896       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 74, 74, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 72, 72, 64)        18496     
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 36, 36, 64)        0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 34, 34, 64)        36928     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 17, 17, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 18496)            

In [55]:
len(train_ge)

8

In [56]:
len(train_ge[0])

2

In [57]:
train_ge[0][0].shape

(4, 150, 150, 3)

In [58]:
model.fit(train_ge,epochs=30,validation_data=test_ge)

Epoch 1/30
8/8 [==============================] - 2s 185ms/step - loss: 1.2730 - accuracy: 0.2000 - val_loss: 1.1616 - val_accuracy: 0.3333
Epoch 2/30
8/8 [==============================] - 1s 140ms/step - loss: 1.1338 - accuracy: 0.2000 - val_loss: 1.0999 - val_accuracy: 0.3333
Epoch 3/30
8/8 [==============================] - 1s 138ms/step - loss: 1.1125 - accuracy: 0.3333 - val_loss: 1.0896 - val_accuracy: 0.2222
Epoch 4/30
8/8 [==============================] - 1s 137ms/step - loss: 1.0976 - accuracy: 0.3000 - val_loss: 1.0676 - val_accuracy: 0.6667
Epoch 5/30
8/8 [==============================] - 1s 139ms/step - loss: 1.1027 - accuracy: 0.3667 - val_loss: 1.0198 - val_accuracy: 0.3333
Epoch 6/30
8/8 [==============================] - 1s 145ms/step - loss: 1.0025 - accuracy: 0.5000 - val_loss: 0.9505 - val_accuracy: 0.7778
Epoch 7/30
8/8 [==============================] - 1s 145ms/step - loss: 1.0118 - accuracy: 0.5333 - val_loss: 0.8396 - val_accuracy: 0.7778
Epoch 8/30
8/8 [====

In [35]:
y_pred = model.predict(test_ge)

In [37]:
for tri in y_pred : 
    print(np.argmax(tri),end=" ")

2 1 1 1 2 1 0 2 0 

In [44]:
test_ge.classes

array([0, 0, 0, 1, 1, 1, 2, 2, 2])